#!/bin/sh

if [ "$#" -lt 1 -o "$#" -gt 2 ]; then
    echo "Usage: $0 <systemd unit> [<mail address>]" >&2
    exit 1
fi

SERVICE="$1"
TO="root@localhost"
if [ -n "$2" ]; then
    TO="$2"
fi

include () {
    test -f "$1" && . "$1"
}

include /usr/etc/default/systemd-status-mail
include /etc/default/systemd-status-mail

HOSTNAME=${HOSTNAME:-$(hostname)}

if [ -z "$FROM" ]; then
    FROM="systemd <root@$HOSTNAME>"
fi

if [ -z "${MAILER}" ]; then
    if [ -x /usr/sbin/sendmail ]; then
	MAILER="sendmail"
    elif [ -x /usr/bin/mailx ]; then
	MAILER="mailx"
    else
	echo "ERROR: $0 - no mail program found!" >&2
    fi
fi

case $MAILER in
    sendmail)
	/usr/sbin/sendmail -t <<EOF
To: $TO
From: $FROM
Subject: $SERVICE ($HOSTNAME)
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=UTF-8

$(systemctl status --lines=500 --full "$SERVICE" 2>&1)
EOF
	;;
    mailx)
	if [ -n "${RELAYHOST}" ]; then
	    RELAY="-Ssmtp=${RELAYHOST}"
	fi
	mailx $MAILX_OPTIONS -Ssendwait -s "$SERVICE ($HOSTNAME)" -r "$FROM" "$RELAY" "$TO" <<EOF
$(systemctl status --lines=500 --full "$SERVICE" 2>&1)
EOF
	;;
    *)
	echo "ERROR: \"$MAILER\" is not a valid entry!" >&2
	echo "       Only \"sendmail\" and \"mailx\" are." >&2
	;;
esac
